_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   /_configurator

api:
    resource: "@ZeegaApiBundle/Resources/config/routing.yml"
    
jda:
    resource: "@ZeegaJDABundle/Resources/config/routing.yml"
